- name: Deploy to EC2
  hosts: localhost
  connection: local

tasks:
  - name: Launch EC2 instance
    ec2:
      instance_type: t2.micro
      image: ami-04902260ca3d33422
      region: us-east-1
      key_name: devops
      vpc_subnet_id: subnet-061b1d9b6a5df5cb4
      assign_public_ip: yes
      count: 1
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
      security_token: "{{session_token}}"